language: go
sudo: required
services:
  - docker

go:
- 1.12

script: 
  - go test ./
  - docker build -t maartje/myip.ninja ./

deploy:
  - provider: script
    script: scripts/deploy.sh
    on:
      branch: master